version: "3"
services:
  database-postgres:
    image: postgres:12.15-bullseye
    container_name: postgres_db
    restart: always
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=university-db"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - database-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - "PGADMIN_DEFAULT_EMAIL=admin@admin.com"
      - "PGADMIN_DEFAULT_PASSWORD=admin"
    ports:
      - "16543:80"
    depends_on:
      - database-postgres
    networks:
      - database-network

  server:
    container_name: university-app
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - database-network

volumes:
  pg-data:

networks:
  database-network:
    driver: bridge